language: php
php: 5.4
install:
  - pecl install rar
  - ./install_dep.sh
cache:
  directories:
  - /usr/local/bin
script:
  - php test.php # unit test
  - ./integration_test.sh
  - ./local_rar_test.sh
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  skip_cleanup: true
  on: 
    all_branches: true
    tags: true
